ServerName localhost
ServerTokens Prod
ServerSignature Off

<VirtualHost *:${PORT}>
    DocumentRoot /var/www/opigno/web
    <Directory /var/www/opigno/web>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    <Directory /data/public>
        Options -Indexes -ExecCGI +FollowSymLinks
        AllowOverride All
        Require all granted
        <FilesMatch "(?i)\.(php[0-9]?|phtml|phar)(\.|$)">
            Require all denied
        </FilesMatch>
    </Directory>
    <LocationMatch "^/(core/install\.php|update\.php)$">
        Require all denied
    </LocationMatch>
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
